schema:
  version: 1.0
  # csv is the only supported format yet
  # Later we'll have support for json and other formats
  csv:
    delimiter: "|"
    multiline: true
    allowQuotes: true
    hasHeader: false
    # auto detect encoding, or specify conforming nodejs supports
    encoding: auto
  # masks define what fields has to be masked and how
  masks:
    # you can set the locale for the masks: https://github.com/marak/Faker.js/#localization
    - field:
        # ref means either column index (starting with 0) or name if hasHeader=true
        ref: claimId
        # type can be anything supported by https://github.com/marak/Faker.js/#api-methods
        type: random.number
        length: 10
    - field:
        ref: 1
        type: date
        # formats supported by https://www.npmjs.com/package/fast-date-format
        format: YYYY/MM/DD
    - field:
        ref: firstName
        type: name.firstName
